* git-hooks
A collection of useful git hooks


** What

A collection of useful git hooks.

- pre-commit: A wrapper hook that lives in and looks in the
  .git/hooks/ dir for other scripts whose name filename begins with
  pre-commit_ and runs those hooks.
- pre-commit_php-01-lint: A hook script to check files with PHP lint. 
- pre-commit_php-02-cs: A hook script to check files against a PHP coding
  standard. 

** Installation and Usage

- clone this repository
- cd into the new directory
- run composer update
- move the content of the hooks/ directory to the .git/hooks/
  directory of your project.

Now when you run git commit the pre-commit script will be executed, it
will find the pre-commit_* script(s) and execute it(them).  

The pre-commit_phpcs script will analyse relevant committed files
against a PHP coding standard and feedback errors and warnings.

In the event that you wish to commit your files regardless of the
standards errors do:

#+BEGIN_SRC sh
git commit --no-verify
#+END_SRC

and git will not execute the pre-commit hooks

** Dependencies

Some scripts require other software available on your system. There is
a composer.json file in this repository. You may use [[https://getcomposer.org][Composer]] to fetch
(most) required software. It will be stored in a newly created vendor
directory. Just issue the command:

#+BEGIN_SRC sh
composer install
#+END_SRC

*** PHP_CodeSniffer
[[https://github.com/squizlabs/PHP_CodeSniffer][PHP_CodeSniffer]] is required by:
- pre-commit_php-02-cs

