* git-hooks
A collection of useful git hooks


** What

A collection of useful git hooks.

- pre-commit: A wrapper hook that lives in and looks in the
  .git/hooks/ dir for other scripts whose name filename begins with
  pre-commit_ and runs those hooks.
- pre-commit_php-01-lint: A hook script to check files with PHP lint. 
- pre-commit_php-02-cs: A hook script to check files against a PHP coding
  standard. Requires phpcs. 

** Installation and Usage

Use git to clone this repository and copy the pre-commit_* files into
your projects .git/hooks/ directory.

Now when you run git commit the pre-commit script will be executed, it
will find the pre-commit_* script(s) and execute it(them).  

The pre-commit_phpcs script will analyse relevant committed files
against a PHP coding standard and feedback errors and warnings.

In the event that you wish to commit your files regardless of the
standards errors do:

#+BEGIN_SRC sh
git commit --no-verify
#+END_SRC

and git will not execute the pre-commit hooks

