#!/bin/bash
#
# place this file in your $GIT_DIR/hooks directory and call it pre-commit
# anyother scripts you want to execture on commit can then also be placed
# in $GIT_DIR/hooks with the correct naming convention.. ie:
# pre-commit_[whatevernameyouwant] make that file executable and this script
# finds it and runs it.
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep -e '\.module' -e '\.inc'`
FILES=${SFILES:-$STAGED_FILES_CMD}

echo "pre-commit hook";
for i in `ls $DIR/pre-commit_*`;
do $i $FILES;
if [ "$?" -ne "0" ]; then
  exit 1
fi
done;

exit 0;
