#!/bin/sh

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
	'
    SFILES="$1"
    IFS=$oIFS
fi

echo "Running PHP Lint..."

echo $SFILES

if [ "$SFILES" != "" ]
then

    for FILE in $SFILES
    do
	php -l -d display_errors=0 $FILE
	if [ $? != 0 ]
	then
	    echo "Fix the error before commit."
    	    exit 1
	fi
    done
fi

exit $?


